# Generated by Django 5.0.1 on 2026-01-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n8n_api_url', models.URLField(default='https://n8n.monoliet.cloud/api/v1', help_text='n8n API base URL', max_length=500)),
                ('n8n_api_key', models.CharField(blank=True, help_text='n8n API authentication key', max_length=500)),
                ('n8n_connection_status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('n8n_last_checked', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(default='Monoliet', help_text='Your company name', max_length=255)),
                ('support_email', models.EmailField(default='info@monoliet.cloud', help_text='Support contact email', max_length=254)),
                ('max_clients', models.IntegerField(default=100, help_text='Maximum number of clients allowed')),
                ('enable_auto_sync', models.BooleanField(default=True, help_text='Automatically sync n8n data')),
                ('sync_interval_minutes', models.IntegerField(default=15, help_text='Minutes between automatic syncs')),
                ('slack_webhook_url', models.URLField(blank=True, help_text='Slack webhook for notifications', max_length=500)),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Send email notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Settings',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='n8n_workflow_url',
            field=models.URLField(blank=True, help_text='Direct link to workflow in n8n editor', max_length=500, null=True),
        ),
    ]
