# Generated by Django 5.0.1 on 2026-01-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_portalsettings_workflow_n8n_workflow_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='mcp_last_health_check',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful MCP server health check', null=True, verbose_name='Last Health Check'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='mcp_server_auth_token',
            field=models.CharField(blank=True, help_text='Authentication token for MCP server API calls (optional, uses portal tokens if empty)', max_length=500, verbose_name='MCP Server Auth Token'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='mcp_server_enabled',
            field=models.BooleanField(default=False, help_text='Enable MCP server management from admin panel', verbose_name='Enable MCP Server Integration'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='mcp_server_status',
            field=models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=50, verbose_name='MCP Server Status'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='mcp_server_url',
            field=models.URLField(blank=True, default='http://localhost:8002', help_text='URL of MCP server management API (e.g., http://mcp-api.monoliet.cloud)', max_length=500, verbose_name='MCP Management API URL'),
        ),
    ]
