# Generated by Django 5.0.1 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_portalsettings_mcp_last_health_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionIntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('entry_type', models.CharField(blank=True, max_length=20, null=True)),
                ('draft', models.JSONField(default=dict)),
                ('history', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
